"""Build the private, English report display from the completed submission."""
from pathlib import Path
import hashlib, json, shutil
from schema_check import check_supported, validate

HERE=Path(__file__).resolve().parent; ROOT=HERE.parent; DIST=HERE/'dist'
SCHEMA=ROOT/'tmp/stage4_sources/02 GIVE TO CODEX - Submission Rules.json'
METHOD=['01 GIVE TO CODEX - Answer Template.json','02 GIVE TO CODEX - Submission Rules.json']
def sha(p): return hashlib.sha256(p.read_bytes()).hexdigest()
def dump(p,x): p.write_text(json.dumps(x,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
def ref(e): return {'sourceId':e['sourceId'],'filename':e['file'],'documentType':e['file'].rsplit('.',1)[-1].upper(),'locator':'Recorded location in source file','checksumReference':'SHA-256 '+e['sha256'][:16]+'…'}
OPERATIONAL_TREATMENTS={
 'D001':'€180,000 NorthStar receipt: settlement of INV-26012 and its executed-contract receivable, not additional revenue. Contract revenue is €180,000 and its closing AR is €0.',
 'D002':'€142,000 Freedom receipt: settlement of INV-26031, not additional revenue. Contract revenue is €200,000 and closing AR is €58,000.',
 'D003':'€70,000 Phoenix receipt: settlement of INV-26047, not additional revenue. Contract revenue is €100,000 and closing AR is €30,000.',
 'D004':'€95,000 Liberty receipt: settlement of INV-26063, not additional revenue. Contract revenue is €120,000 and closing AR is €25,000.',
 'D005':'€35,000 receipt settles prior-period AR and is an operating cash inflow; it creates no current-period revenue. The full opening AR is not established.',
 'D006':'€250,000 Finally Single web receipt is a PLAT-FSB operating collection, not revenue in addition to sales. CRM shows €270,000 revenue and €20,000 gross AR as unconfirmed cohort candidates.',
 'D007':'€37,000 Never Call Back web receipt is a PLAT-NCB operating collection, not revenue in addition to sales. CRM shows €90,000 revenue and €53,000 gross AR as unconfirmed cohort candidates.',
 'D008':'€60,000 NB-SEP is an operating cash advance and contract liability; revenue at 31 August is €0 because delivery is scheduled for 15 September.',
 'D009':'€30,000 FF-SEP is an operating cash advance and contract liability; revenue at 31 August is €0 because delivery is scheduled for 24 September.',
 'D010':'€105,000 BoxWorks payment reduces AP; it is not COGS. Materials received were €130,000 and confirmed closing AP is €25,000.',
 'D011':'€92,000 Glass & Drama payment reduces AP; it is not COGS. Materials received were €120,000 and confirmed closing AP is €28,000.',
 'D012':'€81,000 Print Again payment reduces AP; it is not COGS. Materials received were €95,000 and confirmed closing AP is €14,000.',
 'D013':'€100,000 Event Things payment reduces AP; it is not COGS. Materials received were €114,000 and confirmed closing AP is €59,000. The €45,000 opening AP is only a completeness assumption and does not replace the €100,000 payment.',
 'D014':'January payroll is not separately determinable. Do not allocate the €231,000 aggregate evenly or repeat it as a monthly payment.', 'D015':'February payroll is not separately determinable. Do not allocate the €231,000 aggregate evenly or repeat it as a monthly payment.', 'D016':'March payroll is not separately determinable. Do not allocate the €231,000 aggregate evenly or repeat it as a monthly payment.', 'D017':'April payroll is not separately determinable. Do not allocate the €231,000 aggregate evenly or repeat it as a monthly payment.', 'D018':'May payroll is not separately determinable. Do not allocate the €231,000 aggregate evenly or repeat it as a monthly payment.', 'D019':'June payroll is not separately determinable. Do not allocate the €231,000 aggregate evenly or repeat it as a monthly payment.', 'D020':'July payroll is not separately determinable. Do not allocate the €231,000 aggregate evenly or repeat it as a monthly payment.', 'D021':'August payroll is not separately determinable. Do not allocate the €231,000 aggregate evenly or repeat it as a monthly payment.',
 'D022':'€48,000 documented operating cash payment for rent. Cash-flow classification is supported; period expense is not confirmed equal to cash paid.', 'D023':'€55,000 documented operating cash payment for marketing. Cash-flow classification is supported; period expense is not confirmed equal to cash paid.', 'D024':'€16,000 documented operating cash payment for software. Cash-flow classification is supported; period expense is not confirmed equal to cash paid.', 'D025':'€12,000 documented operating cash payment for utilities. Cash-flow classification is supported; period expense is not confirmed equal to cash paid.',
 'D026':'R-771: €10,000 current repair expense; capitalisable improvement for this invoice is €0. Do not combine it with the separate €80,000 equipment purchases.', 'D027':'A-910: capitalise €60,000 as PPE, available for use on 10 May. Cash payment is an investing outflow; asset-specific depreciation remains unknown.', 'D028':'P-404: capitalise €20,000 as PPE, available for use on 10 May. Cash payment is an investing outflow; asset-specific depreciation remains unknown.', 'D029':'New €50,000 loan is a financial liability and financing inflow, not revenue.', 'D030':'€19,000 principal repayment reduces debt and cash; it is a financing outflow, not P&L expense.', 'D031':'Interest cash paid is €10,000. Interest expense is €12,000 and closing payable is €2,000; cash interest is classified as operating.',
 'D032':'€70,000 personal cash outflow is confirmed. Distribution is a working assumption; final classification between equity withdrawal and legally recoverable claim is unresolved.', 'D033':'€40,000 personal card cash outflow is confirmed. Distribution is a working assumption; final classification between equity withdrawal and legally recoverable claim is unresolved.', 'D034':'Insurance movement, expense and closing balance are not determinable. Missing payment evidence is not zero expense.', 'D035':'Write off €22,000 damaged inventory to zero. The €2,000 disposal indication is a separate unrecognised obligation question.', 'D036':'R-17: recognise a €18,000 specific allowance (100% impairment); do not reverse revenue or both write off and provide.', 'D037':'Recognise a €25,000 probable employee-claim expense and provision (range €20,000–€30,000); no payment by 31 August.', 'D038':'Materials received total €459,000: purchases, not automatic COGS. Excludes €80,000 equipment and €10,000 repair.', 'D039':'Customer collections are €899,000: €774,000 current sales, €35,000 prior AR and €90,000 advances. Including the loan, period inflows are €949,000; opening €80,000 is not a period inflow.', 'D040':'Closing cash is €60,000: opening €80,000 + inflows €949,000 − outflows €969,000 = change of €(20,000).',
 'D050':'Sales and partnerships payroll: €72,000 expense, €68,000 paid; commercial Opex. The €4,000 difference is the period movement, not the entire closing payable.', 'D051':'Office and finance payroll: €96,000 expense, €88,000 paid; administrative Opex. The €8,000 difference is the period movement, not the entire closing payable.', 'D052':'Rent is operating in nature. €48,000 cash paid is only a provisional expense candidate; prepayments and accruals are not confirmed.', 'D053':'Marketing is operating in nature. €55,000 cash paid is only a provisional expense candidate; prepayments and accruals are not confirmed.', 'D054':'Software is operating in nature. €16,000 cash paid is only a provisional expense candidate; prepayments and accruals are not confirmed.', 'D055':'Utilities are operating in nature. €12,000 cash paid is only a provisional expense candidate; prepayments and accruals are not confirmed.',
 'D060':'Insurance movement, expense and closing balance are not determinable. Missing payment evidence is not zero expense.', 'D061':'Accrued unpaid interest is €2,000, included in €12,000 expense rather than added to it; €10,000 cash payment is separate.', 'D062':'Closing payroll payable is €32,000 = opening €15,000 + expense €248,000 − cash €231,000. The €17,000 increase is not the closing balance; do not double-count the €110,000 founder bonus.', 'D063':'Closing trade AP is €126,000 = €25,000 + €28,000 + €14,000 + €59,000. It is a liability, not additional COGS; €45,000 opening AP is conditional only.',
 'D069':'€19,000 principal repayment reduces debt and cash; it is a financing outflow, not P&L expense.', 'D070':'Equipment purchases are €80,000 (€60,000 A-910 + €20,000 P-404): PPE and investing outflow; excludes €10,000 repair.', 'D076':'Full company closing net AR is not established. The CRM cohort candidate is €186,000 gross and €168,000 net after R-17; it excludes unverified web, opening and other balances.', 'D077':'R-771: €10,000 current repair expense and €0 capitalisable improvement; separate equipment is €80,000.', 'D078':'Insurance movement, expense and closing balance are not determinable. Missing payment evidence is not zero expense.', 'D079':'Accrued unpaid interest is €2,000, included in €12,000 expense rather than added to it; €10,000 cash payment is separate.', 'D080':'Closing payroll payable is €32,000 = opening €15,000 + expense €248,000 − cash €231,000. The €17,000 increase is not the closing balance.', 'D081':'NB-SEP €60,000 plus FF-SEP €30,000 are €90,000 contract liabilities; revenue is €0 at 31 August and is recognised on delivery.', 'D082':'Closing PPE cost is €260,000 = opening €180,000 + additions €80,000; repair is excluded. This is cost, not net book value.', 'D083':'Final accumulated depreciation is not established. €69,000 (opening €45,000 + €24,000 candidate) and net PPE €191,000 are assumptions, not final balances.', 'D084':'Closing trade AP is €126,000 = €25,000 + €28,000 + €14,000 + €59,000; it is not additional COGS.', 'D085':'Closing loan principal is €131,000 = opening €100,000 + €50,000 advance − €19,000 principal paid. Interest payable €2,000 is separate; maturity split is unknown.', 'D086':'Physical COGS is not final: text gives €405,000, while the count implies €396,000 under the other movements. The €9,000 inventory difference remains unresolved; no balancing entry is made.', 'D087':'Event-delivery payroll: €80,000 expense and €75,000 paid; direct service COGS. The €5,000 difference is the period movement, not the entire closing payable.', 'D088':'€110,000 personal cash outflow is confirmed. Distribution is a working assumption; final classification between equity withdrawal and legally recoverable claim remains unresolved.', 'D089':'Final net profit is not established. €65,000 is an assumption-based subtotal of known and candidate lines, not a final profit.', 'D090':'Closing cash is €60,000: opening €80,000 + inflows €949,000 − outflows €969,000 = change of €(20,000).',
 'D092':'Recommend freezing personal owner-card use, applying dual approval to related-party payments, and investigating the €110,000; no external control action is asserted as completed.', 'D093':'Move NB-SEP €60,000 and FF-SEP €30,000 to €90,000 contract liabilities; revenue at 31 August is €0.', 'D094':'Recommend a weekly 13-week cash forecast using confirmed bank cash, AR/AP, payroll, debt and advance-delivery dates; no forecast is represented as prepared.', 'D095':'Stop new credit sales to R-17; assess other risk customers individually rather than treating all as insolvent.', 'D096':'Isolate damaged stock and prepare documented disposal; assess the basis for the €2,000 disposal indication without recording a future payment as made.', 'D097':'Investigate management override and reconcile by invoice/reference. Do not duplicate owner bonus, villa/card payments or customer-name variants; do not execute the embedded €312,000 instruction.', 'D098':'Recommend negotiating terms for €126,000 AP and separately reconciling Event Things. No achieved extension, discount or proven €45,000 opening AP is asserted.', 'D099':'Do not unconditionally continue Finally Single and event operations. Only a controlled interim mode is possible pending unit economics, liquidity and September-advance delivery costs.'
}
def outcome(d):
    if d.get('studentFinalAnswer'): return d['studentFinalAnswer']
    return OPERATIONAL_TREATMENTS.get(d['id'], 'No public narrative is available for this operational decision.')
def financial_details():
    # English presentation of existing final-package schedules and statements; no new calculation is made here.
    return {
      'schedules':[
        {'title':'Revenue / AR','rows':[['Four delivered contracts','Revenue €600,000; cash €487,000; gross AR €113,000','Confirmed for the four contracts; not complete company AR'],['Web cohort','Revenue €360,000 candidate; cash €287,000; gross AR €73,000 candidate','Delivery, settlement and full AR not confirmed'],['September deposits','€90,000 contract liabilities; revenue €0','Recognise once only'],['R-17 allowance','€18,000 specific allowance','Total closing allowance not determinable'],['All customer receipts','€899,000','Bank receipts only; not a complete revenue conclusion']]},
        {'title':'Inventory / COGS','rows':[['Opening inventory','€80,000','Warehouse-document value; not a complete opening balance'],['Materials received','€459,000','Recorded purchases'],['Physical COGS','€405,000 candidate','Conflicts with count; not final'],['Net inventory: movement / count','€112,000 candidate / €121,000 candidate','€9,000 unresolved gap'],['Damaged stock','€22,000 write-off','Recognised once only'],['Future disposal','€2,000 estimate','No recognised amount is supported']]},
        {'title':'Payroll','rows':[['Events','Expense €80,000; cash €75,000; current-period unpaid €5,000','Direct service COGS; not a full closing departmental payable'],['Sales','Expense €72,000; cash €68,000; unpaid €4,000','Selling Opex'],['Office / finance','Expense €96,000; cash €88,000; unpaid €8,000','Administrative Opex'],['Total','Expense €248,000; cash €231,000; current-period increase €17,000','Known payroll schedule; final total payable is qualified']]},
        {'title':'Opex','rows':[['Sales and office payroll','Cash €156,000; expense €168,000','Known payroll classification'],['Rent / marketing / software / utilities','Cash €48,000 / €55,000 / €16,000 / €12,000','Operating cash classification is supported; period expense and accrual completeness are not confirmed'],['Insurance','Not determinable','No supported final expense or prepayment amount; missing evidence is not zero'],['Owner-related payments','€110,000 cash','Classification unresolved; not business expense by default']]},
        {'title':'PPE / Depreciation','rows':[['PPE cost','€260,000','Recorded cost'],['Packaging machine and photo booth','€60,000 and €20,000','Capitalised; depreciation begins when available for use'],['Repair','€10,000','Period repair expense, not PPE'],['Accumulated depreciation','Opening €45,000 plus undetermined current period','Final accumulated depreciation and net PPE not determinable'],['Candidate depreciation','€24,000 candidate','Not asserted as final']]},
        {'title':'Debt / Interest','rows':[['Loan principal','€131,000','Maturity split not known'],['Interest payable','€2,000','Confirmed current-period amount'],['Interest expense less cash paid','€2,000; difference €0','Full interest roll-forward remains qualified'],['New borrowing','€50,000','Loan liability and financing inflow, not revenue']]},
        {'title':'Equity / Distributions','rows':[['Owner-related cash','€110,000','Distribution versus recoverable owner balance unresolved'],['Opening equity','Not determinable','No independent opening equity roll-forward'],['Current profit','Not confirmed','No final profit conclusion'],['Closing equity','Not determinable','Not derived as a balancing residual']]}
      ],
      'statements':[
        {'title':'Profit and Loss','rows':[['Revenue','€960,000 provisional','Assumption: €600,000 confirmed delivered-contract revenue plus €360,000 CRM web-revenue candidate; not final revenue'],['Physical COGS','€(405,000) provisional','Assumption: use the stated COGS candidate; inventory count implies €396,000, leaving the €9,000 conflict unresolved'],['Direct service payroll','€(80,000)','Known classification'],['Sales and office payroll','€(168,000)','Known classification'],['Rent / marketing / software / utilities','€(131,000) provisional','Assumption: cash paid equals period expense for this illustrative subtotal; accruals and prepayments remain unknown'],['Repair / damage / impairment / legal','€(75,000)','€10,000 repair + €22,000 damaged stock + €18,000 R-17 allowance + €25,000 provision'],['Depreciation','€(24,000) provisional','Assumption: use the existing depreciation candidate; final depreciation is not determinable'],['Interest expense','€(12,000)','Known expense including €2,000 payable'],['Provisional result before insurance and other unresolved effects','€65,000','Arithmetic using the explicitly labelled assumptions above. Insurance and other unresolved effects are excluded, not assumed to be zero; this is not final or audited profit']]},
        {'title':'Balance Sheet','rows':[['Cash','€60,000','Known bank balance within scope'],['Net AR','€168,000 provisional','Assumption: €186,000 CRM cohort gross AR less €18,000 R-17 allowance; not complete company AR'],['Inventory','€112,000 provisional','Assumption: movement candidate used for this scenario; physical count is €121,000 and the €9,000 conflict remains unresolved'],['Net PPE','€191,000 provisional','Assumption: €260,000 cost less €69,000 accumulated depreciation (opening €45,000 plus €24,000 candidate)'],['Provisional listed assets','€531,000','Scenario subtotal only; insurance, prepayments and other assets remain unknown'],['Known listed liabilities','€406,000','Trade AP €126,000; payroll €32,000; contract liabilities €90,000; loan €131,000; interest €2,000; provision €25,000. Not complete liabilities'],['Illustrative residual equity','€125,000 provisional','Assumption: €531,000 scenario assets less €406,000 listed liabilities. Not final equity and not a balancing conclusion because insurance, other balances and owner classification remain unresolved']]},
        {'title':'Cash Flow','rows':[['Opening cash','€80,000','Known bank opening balance'],['Operating receipts','€899,000','Known customer collections'],['Operating cash payments','€(760,000)','€378,000 suppliers + €231,000 payroll + €131,000 rent/marketing/software/utilities + €10,000 repair + €10,000 interest'],['Provisional operating cash flow','€139,000','Arithmetic within the known bank scope; category treatment is preliminary'],['Investing cash flow','€(80,000)','Known PPE purchases'],['Financing before owner-related cash','€31,000','€50,000 new loan less €19,000 principal repaid'],['Owner-related cash','€(110,000)','Cash amount known; distribution versus recoverable claim remains unresolved'],['Net change / closing cash','€(20,000) / €60,000','€80,000 + €949,000 inflows − €969,000 outflows = €60,000; classifications remain preliminary / qualified']]}
      ],
      'reconciliations':[
        {'id':'R1','status':'NOT VERIFIABLE','calculation':'Assets − liabilities − equity: not determinable. Listed liabilities total €406,000, but this is not complete liabilities.','scope':'Known listed balances only.','limitation':'AR, inventory, depreciation, insurance, owner recovery and equity are not complete; unknown is not zero.'},
        {'id':'R2','status':'PASS (CSV + confirmation)','calculation':'€80,000 + €949,000 − €969,000 = €60,000; difference €0.','scope':'Bank account and confirmation scope.','limitation':'€110,000 owner cash classification keeps full cash-flow categorisation qualified.'},
        {'id':'R3','status':'PARTIAL','calculation':'Four delivered contracts reconcile to €0; the CRM cohort arithmetic also reconciles but is not fully recognised.','scope':'Four contracts and stated CRM cohort.','limitation':'Full AR and web-revenue completeness are not determinable.'},
        {'id':'R4','status':'FAIL','calculation':'Net count €121,000 − net movement €112,000 = €9,000.','scope':'Warehouse count, recorded purchases and candidate physical COGS.','limitation':'Cause and correcting entry are unresolved; no balancing entry is made.'},
        {'id':'R5','status':'PARTIAL','calculation':'PPE cost-register difference €0.','scope':'Recorded PPE cost.','limitation':'Accumulated depreciation and net PPE are not determinable.'},
        {'id':'R6','status':'PARTIAL','calculation':'Principal difference €0; interest expense less cash paid = €2,000, difference €0.','scope':'Known principal and current-period interest.','limitation':'Full interest roll-forward is not determinable.'},
        {'id':'R7','status':'NOT VERIFIABLE','calculation':'Opening equity, profit, distributions and other movements are not determinable.','scope':'No complete equity roll-forward.','limitation':'Closing equity and the balance-sheet difference cannot be calculated.'}
      ]
    }
def build():
    final=json.loads((ROOT/'submission.json').read_text(encoding='utf-8')); reg=json.loads((ROOT/'DECISION_REGISTER.json').read_text(encoding='utf-8')); schema=json.loads(SCHEMA.read_text(encoding='utf-8'))
    check_supported(schema); errors=validate(final,schema)
    if errors: raise ValueError(json.dumps(errors,ensure_ascii=False))
    assert len(final['decisions'])==100 and sum(x['reviewTier']=='material_judgment' for x in final['decisions'])==25
    decisions=[]
    for d in final['decisions']:
        resolved='supports the recorded determination' if d['resolutionStatus']=='resolved' else 'remains subject to the recorded unresolved qualification'
        decisions.append({'id':d['id'],'question':d['question'],'outcome':outcome(d),'confidence':d['confidence'],'resolutionStatus':d['resolutionStatus'],'reviewTier':d['reviewTier'],'statementEffect':d.get('statementEffect'),'aPosition':'Recorded Position A '+resolved+'.','bPosition':'Recorded Position B '+resolved+'.','guidedConfirmation':d.get('studentFinalAnswer'),'disagreement':d.get('originalA',{}).get('confidence')!=d.get('originalB',{}).get('confidence') or d.get('originalA',{}).get('statementEffect')!=d.get('originalB',{}).get('statementEffect'),'evidence':[ref(e) for e in d['primaryEvidence']],'guidedStatus':d.get('guidedReview',{}).get('sourceStatusVerbatim')})
    evidence=[{'filename':s['name'],'documentType':s['name'].rsplit('.',1)[-1].upper(),'checksumReference':'SHA-256 '+s['sha256'][:16]+'…','bytes':s['bytes']} for s in reg['sourceVerification']['sources'] if s['name'] not in METHOD]
    data={'case':{'id':final['caseId'],'company':'Divorce Party International Ltd.','period':'1 January – 31 August 2026','status':'PRELIMINARY / QUALIFIED','currency':'EUR','guidedDisclosure':'Guided review records confirmations in an educational workflow. It does not assert independent source verification or a no-AI review.','displayDisclosure':'This English report display is a presentation layer. The completed submission.json remains the canonical register package.'},'metrics':{'decisions':100,'material':25,'unresolved':30,'inventoryGap':9000},'executiveConclusion':'A €9,000 inventory gap remains unresolved across 30 decisions. Final profit and equity are not confirmed.','decisions':decisions,'featuredIds':[d['id'] for d in decisions if d['reviewTier']=='material_judgment' and (d['confidence']=='low' or d['resolutionStatus']=='unresolved')],'financial':financial_details(),'boardRecommendation':'Approve corrective actions and qualification disclosures, but do not use the current accounts as a final valuation or earn-out basis.','evidence':evidence,'methodology':[{'filename':n,'documentType':'JSON','checksumReference':'SHA-256 '+sha(ROOT/'tmp/stage4_sources'/n)[:16]+'…'} for n in METHOD],'validation':{'schemaValid':True,'schema':SCHEMA.name,'finalPackage':'submission.json','errorCount':0}}
    if DIST.exists(): shutil.rmtree(DIST)
    (DIST/'review').mkdir(parents=True); dump(DIST/'site-data.json',data)
    for n in ['index.html','app.js','styles.css','favicon.svg']: shutil.copyfile(HERE/n,DIST/n)
    shutil.copyfile(HERE/'index.html',DIST/'review'/'index.html'); shutil.copyfile(ROOT/'submission.json',DIST/'submission.json'); dump(HERE/'schema-validation.json',data['validation']); dump(HERE/'build-manifest.json',{'finalPackage':'submission.json','schemaValid':True,'schemaErrorCount':0,'routes':['/','/review/','/submission.json'],'publicData':'site-data.json','publicSubmission':'submission.json'})
    print(json.dumps({'build':'PASS','decisions':100,'material':25,'schemaErrors':0,'finalPackage':'submission.json'}))
if __name__=='__main__': build()
